[package]
name = "ohm-demo"
entry = "main.coil"

[dependencies]
ohm = { path = "../../dialects/ohm" }

[readers]
".ohm" = "experiments.ohm.cst"

[modules]
"experiments.ohm-demo.arithmetic" = "arithmetic.ohm"
