[package]
name = "experiments"
entry = "main.coil"
source-roots = [".", "../../dialects/c"]

[build]
out = "raylib-demo"

[manifest.providers]
c = "experiments.c.reader"

[readers]
".h" = "experiments.c.reader"

[modules]
"experiments.raylib-demo.raylib" = "vendor/raylib/src/raylib.h"

[c.raylib]
sources = [
  "vendor/raylib/src/rcore.c",
  "vendor/raylib/src/rshapes.c",
  "vendor/raylib/src/rtextures.c",
  "vendor/raylib/src/rtext.c",
  "vendor/raylib/src/rmodels.c",
  "vendor/raylib/src/raudio.c",
  "vendor/raylib/src/utils.c",
]
include-paths = [
  "vendor/raylib/src",
  "/opt/homebrew/opt/sdl2-compat/include/SDL2",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/21/include",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks",
]
prefixes = [
  "../../dialects/c/target/darwin-arm64.h",
  "../../dialects/c/target/builtins.h",
]
defines = [
  "STBIR_NO_SIMD",
  "MA_NO_NEON",
  "MA_DR_FLAC_NO_NEON",
  "DR_MP3_NO_SIMD",
  "__ARM_NEON_H",
  "__ARM_BF16_H",
  "SDL_DISABLE_ARM_NEON_H",
  "PLATFORM_DESKTOP_SDL",
  "GRAPHICS_API_OPENGL_33",
  "_FORTIFY_SOURCE=0",
]

[link]
frameworks = ["AppKit", "QuartzCore", "CoreGraphics", "CoreText", "CoreVideo", "ImageIO", "CoreFoundation", "Metal", "OpenGL", "CoreAudio", "AudioToolbox"]
libs = ["objc", "SDL2"]
