[package]
name = "emacs"
entry = "main.coil"
source-roots = [".", "../../dialects/c"]

[build]
out = "emacs-coil"
optimization = 2

[manifest.providers]
c = "experiments.c.reader"

[readers]
".h" = "experiments.c.reader"

[modules]
"experiments.emacs.core" = "emacs.h"

[c.emacs]
sources = [
  "vendor/emacs/lib/fingerprint.c",
  "vendor/emacs/lib/acl_entries.c",
  "vendor/emacs/lib/memmem.c",
  "vendor/emacs/lib/mktime.c",
  "vendor/emacs/lib/acl-errno-valid.c",
  "vendor/emacs/lib/acl-internal.c",
  "vendor/emacs/lib/get-permissions.c",
  "vendor/emacs/lib/set-permissions.c",
  "vendor/emacs/lib/allocator.c",
  "vendor/emacs/lib/openat-proc.c",
  "vendor/emacs/lib/binary-io.c",
  "vendor/emacs/lib/boot-time.c",
  "vendor/emacs/lib/byteswap.c",
  "vendor/emacs/lib/c-ctype.c",
  "vendor/emacs/lib/c-strcasecmp.c",
  "vendor/emacs/lib/c-strncasecmp.c",
  "vendor/emacs/lib/canonicalize-lgpl.c",
  "vendor/emacs/lib/careadlinkat.c",
  "vendor/emacs/lib/close-stream.c",
  "vendor/emacs/lib/copy-file-range.c",
  "vendor/emacs/lib/md5-stream.c",
  "vendor/emacs/lib/md5.c",
  "vendor/emacs/lib/sha1.c",
  "vendor/emacs/lib/sha256.c",
  "vendor/emacs/lib/sha512.c",
  "vendor/emacs/lib/dtoastr.c",
  "vendor/emacs/lib/dtotimespec.c",
  "vendor/emacs/lib/endian.c",
  "vendor/emacs/lib/file-has-acl.c",
  "vendor/emacs/lib/filemode.c",
  "vendor/emacs/lib/filevercmp.c",
  "vendor/emacs/lib/fpending.c",
  "vendor/emacs/lib/free.c",
  "vendor/emacs/lib/fstatat.c",
  "vendor/emacs/lib/fsusage.c",
  "vendor/emacs/lib/futimens.c",
  "vendor/emacs/lib/getopt.c",
  "vendor/emacs/lib/getopt1.c",
  "vendor/emacs/lib/getrandom.c",
  "vendor/emacs/lib/gettime.c",
  "vendor/emacs/lib/malloc/dynarray_at_failure.c",
  "vendor/emacs/lib/malloc/dynarray_emplace_enlarge.c",
  "vendor/emacs/lib/malloc/dynarray_finalize.c",
  "vendor/emacs/lib/malloc/dynarray_resize.c",
  "vendor/emacs/lib/malloc/dynarray_resize_clear.c",
  "vendor/emacs/lib/malloc/scratch_buffer_grow.c",
  "vendor/emacs/lib/malloc/scratch_buffer_grow_preserve.c",
  "vendor/emacs/lib/malloc/scratch_buffer_set_array_size.c",
  "vendor/emacs/lib/mini-gmp-gnulib.c",
  "vendor/emacs/lib/lstat.c",
  "vendor/emacs/lib/mempcpy.c",
  "vendor/emacs/lib/memrchr.c",
  "vendor/emacs/lib/memset_explicit.c",
  "vendor/emacs/lib/nanosleep.c",
  "vendor/emacs/lib/nproc.c",
  "vendor/emacs/lib/nstrftime.c",
  "vendor/emacs/lib/pipe2.c",
  "vendor/emacs/lib/qcopy-acl.c",
  "vendor/emacs/lib/rawmemchr.c",
  "vendor/emacs/lib/sig2str.c",
  "vendor/emacs/lib/sigdescr_np.c",
  "vendor/emacs/lib/stat-time.c",
  "vendor/emacs/lib/stdbit.c",
  "vendor/emacs/lib/stdc_bit_width.c",
  "vendor/emacs/lib/stdc_count_ones.c",
  "vendor/emacs/lib/stdc_leading_zeros.c",
  "vendor/emacs/lib/stdc_trailing_zeros.c",
  "vendor/emacs/lib/tempname.c",
  "vendor/emacs/lib/time_rz.c",
  "vendor/emacs/lib/timegm.c",
  "vendor/emacs/lib/timespec.c",
  "vendor/emacs/lib/timespec-add.c",
  "vendor/emacs/lib/timespec-sub.c",
  "vendor/emacs/lib/u64.c",
  "vendor/emacs/lib/unistd.c",
  "vendor/emacs/lib/utimens.c",
  "vendor/emacs/lib/utimensat.c",
  "vendor/emacs/lib/openat-die.c",
  "vendor/emacs/lib/save-cwd.c",
  "vendor/emacs/src/dispnew.c",
  "vendor/emacs/src/frame.c",
  "vendor/emacs/src/scroll.c",
  "vendor/emacs/src/xdisp.c",
  "vendor/emacs/src/menu.c",
  "vendor/emacs/src/window.c",
  "vendor/emacs/src/charset.c",
  "vendor/emacs/src/coding.c",
  "vendor/emacs/src/category.c",
  "vendor/emacs/src/ccl.c",
  "vendor/emacs/src/character.c",
  "vendor/emacs/src/chartab.c",
  "vendor/emacs/src/bidi.c",
  "vendor/emacs/src/cm.c",
  "vendor/emacs/src/term.c",
  "vendor/emacs/src/terminal.c",
  "vendor/emacs/src/xfaces.c",
  "vendor/emacs/src/emacs.c",
  "vendor/emacs/src/keyboard.c",
  "vendor/emacs/src/macros.c",
  "vendor/emacs/src/keymap.c",
  "vendor/emacs/src/sysdep.c",
  "vendor/emacs/src/bignum.c",
  "vendor/emacs/src/buffer.c",
  "vendor/emacs/src/filelock.c",
  "vendor/emacs/src/insdel.c",
  "vendor/emacs/src/marker.c",
  "vendor/emacs/src/minibuf.c",
  "vendor/emacs/src/fileio.c",
  "vendor/emacs/src/dired.c",
  "vendor/emacs/src/cmds.c",
  "vendor/emacs/src/casetab.c",
  "vendor/emacs/src/casefiddle.c",
  "vendor/emacs/src/indent.c",
  "vendor/emacs/src/search.c",
  "vendor/emacs/src/regex-emacs.c",
  "vendor/emacs/src/undo.c",
  "vendor/emacs/src/alloc.c",
  "vendor/emacs/src/pdumper.c",
  "vendor/emacs/src/data.c",
  "vendor/emacs/src/doc.c",
  "vendor/emacs/src/editfns.c",
  "vendor/emacs/src/callint.c",
  "vendor/emacs/src/eval.c",
  "vendor/emacs/src/floatfns.c",
  "vendor/emacs/src/fns.c",
  "vendor/emacs/src/sort.c",
  "vendor/emacs/src/font.c",
  "vendor/emacs/src/print.c",
  "vendor/emacs/src/lread.c",
  "vendor/emacs/src/emacs-module.c",
  "vendor/emacs/src/syntax.c",
  "vendor/emacs/src/bytecode.c",
  "vendor/emacs/src/comp.c",
  "vendor/emacs/src/dynlib.c",
  "vendor/emacs/src/process.c",
  "vendor/emacs/src/gnutls.c",
  "vendor/emacs/src/callproc.c",
  "vendor/emacs/src/region-cache.c",
  "vendor/emacs/src/sound.c",
  "vendor/emacs/src/timefns.c",
  "vendor/emacs/src/atimer.c",
  "vendor/emacs/src/doprnt.c",
  "vendor/emacs/src/intervals.c",
  "vendor/emacs/src/textprop.c",
  "vendor/emacs/src/composite.c",
  "vendor/emacs/src/xml.c",
  "vendor/emacs/src/lcms.c",
  "vendor/emacs/src/kqueue.c",
  "vendor/emacs/src/profiler.c",
  "vendor/emacs/src/decompress.c",
  "vendor/emacs/src/thread.c",
  "vendor/emacs/src/systhread.c",
  "vendor/emacs/src/sqlite.c",
  "vendor/emacs/src/treesit.c",
  "vendor/emacs/src/itree.c",
  "vendor/emacs/src/json.c",
  "vendor/emacs/src/ftfont.c",
  "vendor/emacs/src/hbfont.c",
  "vendor/emacs/src/fontset.c",
  "vendor/emacs/src/fringe.c",
  "vendor/emacs/src/image.c",
  "vendor/emacs/src/terminfo.c",
  "vendor/emacs/src/lastfile.c",
]
include-paths = [
  "target/darwin-arm64/src",
  "target/darwin-arm64/lib",
  "vendor/emacs/src",
  "vendor/emacs/lib",
  "vendor/emacs/lib/malloc",
  "/opt/homebrew/opt/llvm/include",
  "/opt/homebrew/opt/openssl@3/include",
  "/opt/homebrew/opt/gnutls/include",
  "/opt/homebrew/opt/freetype/include/freetype2",
  "/opt/homebrew/opt/fontconfig/include",
  "/opt/homebrew/opt/harfbuzz/include/harfbuzz",
  "/opt/homebrew/opt/libxml2/include/libxml2",
  "/opt/homebrew/opt/little-cms2/include",
  "/opt/homebrew/opt/tree-sitter/include",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/21/include",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks",
]
prefixes = [
  "../../dialects/c/target/darwin-arm64.h",
  "../../dialects/c/target/builtins.h",
]
defines = [
  "HAVE_CONFIG_H",
  "BYTE_CODE_SAFE=1",
  "FT_SIZEOF_INT=4",
  "FT_SIZEOF_LONG=8",
  "FT_SIZEOF_LONG_LONG=8",
]
header-defines = []

[link]
libs = ["xml2", "ncurses", "freetype", "fontconfig", "harfbuzz", "gnutls", "lcms2", "z", "tree-sitter", "sqlite3", "jimbackend"]
search-paths = [
  "/opt/homebrew/opt/gnutls/lib",
  "/opt/homebrew/opt/freetype/lib",
  "/opt/homebrew/opt/fontconfig/lib",
  "/opt/homebrew/opt/harfbuzz/lib",
  "/opt/homebrew/opt/little-cms2/lib",
  "/opt/homebrew/opt/tree-sitter/lib",
  "vendor/emacs/jim-backend",
]
