[package]
name = "curl-demo"
entry = "main.coil"
source-roots = [".", "../../dialects/c"]

[build]
out = "curl-demo"
optimization = 2

[manifest.providers]
c = "experiments.c.reader"

[readers]
".h" = "experiments.c.reader"

[modules]
"experiments.curl-demo.curl" = "vendor/curl/include/curl/curl.h"
"experiments.curl-demo.curl-cli" = "curl_cli.h"

[c.curl]
sources = [
  "vendor/curl/lib/altsvc.c",
  "vendor/curl/lib/amigaos.c",
  "vendor/curl/lib/api.c",
  "vendor/curl/lib/bufq.c",
  "vendor/curl/lib/bufref.c",
  "vendor/curl/lib/cf-h1-proxy.c",
  "vendor/curl/lib/cf-h2-proxy.c",
  "vendor/curl/lib/cf-haproxy.c",
  "vendor/curl/lib/cf-https-connect.c",
  "vendor/curl/lib/cf-ip-happy.c",
  "vendor/curl/lib/cf-recvbuf.c",
  "vendor/curl/lib/cf-setup.c",
  "vendor/curl/lib/cf-socket.c",
  "vendor/curl/lib/cfilters.c",
  "vendor/curl/lib/conncache.c",
  "vendor/curl/lib/connect.c",
  "vendor/curl/lib/content_encoding.c",
  "vendor/curl/lib/cookie.c",
  "vendor/curl/lib/creds.c",
  "vendor/curl/lib/cshutdn.c",
  "vendor/curl/lib/curl_addrinfo.c",
  "vendor/curl/lib/curl_ed25519.c",
  "vendor/curl/lib/curl_endian.c",
  "vendor/curl/lib/curl_fnmatch.c",
  "vendor/curl/lib/curl_fopen.c",
  "vendor/curl/lib/curl_get_line.c",
  "vendor/curl/lib/curl_gethostname.c",
  "vendor/curl/lib/curl_gssapi.c",
  "vendor/curl/lib/curl_memrchr.c",
  "vendor/curl/lib/curl_ntlm_core.c",
  "vendor/curl/lib/curl_range.c",
  "vendor/curl/lib/curl_sasl.c",
  "vendor/curl/lib/curl_sha512_256.c",
  "vendor/curl/lib/curl_share.c",
  "vendor/curl/lib/curl_sspi.c",
  "vendor/curl/lib/curl_threads.c",
  "vendor/curl/lib/curl_trc.c",
  "vendor/curl/lib/curlx/base64.c",
  "vendor/curl/lib/curlx/basename.c",
  "vendor/curl/lib/curlx/dynbuf.c",
  "vendor/curl/lib/curlx/fopen.c",
  "vendor/curl/lib/curlx/inet_ntop.c",
  "vendor/curl/lib/curlx/inet_pton.c",
  "vendor/curl/lib/curlx/multibyte.c",
  "vendor/curl/lib/curlx/nonblock.c",
  "vendor/curl/lib/curlx/snprintf.c",
  "vendor/curl/lib/curlx/strcopy.c",
  "vendor/curl/lib/curlx/strdup.c",
  "vendor/curl/lib/curlx/strerr.c",
  "vendor/curl/lib/curlx/strparse.c",
  "vendor/curl/lib/curlx/timediff.c",
  "vendor/curl/lib/curlx/timeval.c",
  "vendor/curl/lib/curlx/version_win32.c",
  "vendor/curl/lib/curlx/wait.c",
  "vendor/curl/lib/curlx/warnless.c",
  "vendor/curl/lib/curlx/winapi.c",
  "vendor/curl/lib/cw-out.c",
  "vendor/curl/lib/cw-pause.c",
  "vendor/curl/lib/dict.c",
  "vendor/curl/lib/dynhds.c",
  "vendor/curl/lib/easy.c",
  "vendor/curl/lib/easygetopt.c",
  "vendor/curl/lib/easyoptions.c",
  "vendor/curl/lib/escape.c",
  "vendor/curl/lib/fake_addrinfo.c",
  "vendor/curl/lib/file.c",
  "vendor/curl/lib/fileinfo.c",
  "vendor/curl/lib/formdata.c",
  "vendor/curl/lib/ftp.c",
  "vendor/curl/lib/ftplistparser.c",
  "vendor/curl/lib/getenv.c",
  "vendor/curl/lib/getinfo.c",
  "vendor/curl/lib/gopher.c",
  "vendor/curl/lib/hash.c",
  "vendor/curl/lib/headers.c",
  "vendor/curl/lib/hmac.c",
  "vendor/curl/lib/hsts.c",
  "vendor/curl/lib/http.c",
  "vendor/curl/lib/http1.c",
  "vendor/curl/lib/http2.c",
  "vendor/curl/lib/http_aws_sigv4.c",
  "vendor/curl/lib/http_chunks.c",
  "vendor/curl/lib/http_digest.c",
  "vendor/curl/lib/http_httpsig.c",
  "vendor/curl/lib/http_negotiate.c",
  "vendor/curl/lib/http_ntlm.c",
  "vendor/curl/lib/http_proxy.c",
  "vendor/curl/lib/idn.c",
  "vendor/curl/lib/if2ip.c",
  "vendor/curl/lib/imap.c",
  "vendor/curl/lib/ldap.c",
  "vendor/curl/lib/llist.c",
  "vendor/curl/lib/macos.c",
  "vendor/curl/lib/md4.c",
  "vendor/curl/lib/md5.c",
  "vendor/curl/lib/memdebug.c",
  "vendor/curl/lib/mime.c",
  "vendor/curl/lib/mprintf.c",
  "vendor/curl/lib/mqtt.c",
  "vendor/curl/lib/multi.c",
  "vendor/curl/lib/multi_ev.c",
  "vendor/curl/lib/multi_ntfy.c",
  "vendor/curl/lib/netrc.c",
  "vendor/curl/lib/openldap.c",
  "vendor/curl/lib/parsedate.c",
  "vendor/curl/lib/peer.c",
  "vendor/curl/lib/pingpong.c",
  "vendor/curl/lib/pop3.c",
  "vendor/curl/lib/progress.c",
  "vendor/curl/lib/protocol.c",
  "vendor/curl/lib/proxy.c",
  "vendor/curl/lib/psl.c",
  "vendor/curl/lib/rand.c",
  "vendor/curl/lib/ratelimit.c",
  "vendor/curl/lib/request.c",
  "vendor/curl/lib/rtsp.c",
  "vendor/curl/lib/select.c",
  "vendor/curl/lib/sendf.c",
  "vendor/curl/lib/setopt.c",
  "vendor/curl/lib/sha256.c",
  "vendor/curl/lib/slist.c",
  "vendor/curl/lib/smb.c",
  "vendor/curl/lib/smtp.c",
  "vendor/curl/lib/socketpair.c",
  "vendor/curl/lib/socks.c",
  "vendor/curl/lib/socks_gssapi.c",
  "vendor/curl/lib/socks_sspi.c",
  "vendor/curl/lib/splay.c",
  "vendor/curl/lib/strcase.c",
  "vendor/curl/lib/strequal.c",
  "vendor/curl/lib/strerror.c",
  "vendor/curl/lib/system_win32.c",
  "vendor/curl/lib/telnet.c",
  "vendor/curl/lib/tftp.c",
  "vendor/curl/lib/thrdpool.c",
  "vendor/curl/lib/thrdqueue.c",
  "vendor/curl/lib/transfer.c",
  "vendor/curl/lib/uint-bset.c",
  "vendor/curl/lib/uint-hash.c",
  "vendor/curl/lib/uint-hashset.c",
  "vendor/curl/lib/uint-spbset.c",
  "vendor/curl/lib/uint-table.c",
  "vendor/curl/lib/url.c",
  "vendor/curl/lib/urlapi.c",
  "vendor/curl/lib/vauth/cleartext.c",
  "vendor/curl/lib/vauth/cram.c",
  "vendor/curl/lib/vauth/digest.c",
  "vendor/curl/lib/vauth/digest_sspi.c",
  "vendor/curl/lib/vauth/gsasl.c",
  "vendor/curl/lib/vauth/krb5_gssapi.c",
  "vendor/curl/lib/vauth/krb5_sspi.c",
  "vendor/curl/lib/vauth/ntlm.c",
  "vendor/curl/lib/vauth/ntlm_sspi.c",
  "vendor/curl/lib/vauth/oauth2.c",
  "vendor/curl/lib/vauth/spnego_gssapi.c",
  "vendor/curl/lib/vauth/spnego_sspi.c",
  "vendor/curl/lib/vauth/vauth.c",
  "vendor/curl/lib/vdns/asyn-ares.c",
  "vendor/curl/lib/vdns/asyn-base.c",
  "vendor/curl/lib/vdns/asyn-thrdd.c",
  "vendor/curl/lib/vdns/cf-dns.c",
  "vendor/curl/lib/vdns/dnscache.c",
  "vendor/curl/lib/vdns/doh.c",
  "vendor/curl/lib/vdns/hostip.c",
  "vendor/curl/lib/vdns/hostip4.c",
  "vendor/curl/lib/vdns/hostip6.c",
  "vendor/curl/lib/vdns/httpsrr.c",
  "vendor/curl/lib/version.c",
  "vendor/curl/lib/vquic/capsule.c",
  "vendor/curl/lib/vquic/cf-capsule.c",
  "vendor/curl/lib/vquic/cf-ngtcp2-cmn.c",
  "vendor/curl/lib/vquic/cf-ngtcp2-proxy.c",
  "vendor/curl/lib/vquic/cf-ngtcp2.c",
  "vendor/curl/lib/vquic/cf-quiche.c",
  "vendor/curl/lib/vquic/vquic-tls.c",
  "vendor/curl/lib/vquic/vquic.c",
  "vendor/curl/lib/vssh/libssh.c",
  "vendor/curl/lib/vssh/libssh2.c",
  "vendor/curl/lib/vssh/vssh.c",
  "vendor/curl/lib/vtls/apple.c",
  "vendor/curl/lib/vtls/cipher_suite.c",
  "vendor/curl/lib/vtls/gtls.c",
  "vendor/curl/lib/vtls/hostcheck.c",
  "vendor/curl/lib/vtls/keylog.c",
  "vendor/curl/lib/vtls/mbedtls.c",
  "vendor/curl/lib/vtls/openssl.c",
  "vendor/curl/lib/vtls/rustls.c",
  "vendor/curl/lib/vtls/schannel.c",
  "vendor/curl/lib/vtls/schannel_verify.c",
  "vendor/curl/lib/vtls/vtls.c",
  "vendor/curl/lib/vtls/vtls_config.c",
  "vendor/curl/lib/vtls/vtls_scache.c",
  "vendor/curl/lib/vtls/vtls_spack.c",
  "vendor/curl/lib/vtls/wolfssl.c",
  "vendor/curl/lib/vtls/x509asn1.c",
  "vendor/curl/lib/ws.c",
]
include-paths = [
  "target/darwin-arm64",
  "vendor/curl/include",
  "vendor/curl/lib",
  "/opt/homebrew/opt/openssl@3/include",
  "/opt/homebrew/opt/libssh2/include",
  "/opt/homebrew/opt/libnghttp2/include",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/21/include",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks",
]
prefixes = [
  "../../dialects/c/target/darwin-arm64.h",
  "../../dialects/c/target/builtins.h",
]
defines = [
  "BUILDING_LIBCURL",
  "CURL_HIDDEN_SYMBOLS",
  "HAVE_CONFIG_H",
]
header-defines = []


[c.curl_cli]
sources = [
  "vendor/curl/lib/altsvc.c",
  "vendor/curl/lib/amigaos.c",
  "vendor/curl/lib/api.c",
  "vendor/curl/lib/bufq.c",
  "vendor/curl/lib/bufref.c",
  "vendor/curl/lib/cf-h1-proxy.c",
  "vendor/curl/lib/cf-h2-proxy.c",
  "vendor/curl/lib/cf-haproxy.c",
  "vendor/curl/lib/cf-https-connect.c",
  "vendor/curl/lib/cf-ip-happy.c",
  "vendor/curl/lib/cf-recvbuf.c",
  "vendor/curl/lib/cf-setup.c",
  "vendor/curl/lib/cf-socket.c",
  "vendor/curl/lib/cfilters.c",
  "vendor/curl/lib/conncache.c",
  "vendor/curl/lib/connect.c",
  "vendor/curl/lib/content_encoding.c",
  "vendor/curl/lib/cookie.c",
  "vendor/curl/lib/creds.c",
  "vendor/curl/lib/cshutdn.c",
  "vendor/curl/lib/curl_addrinfo.c",
  "vendor/curl/lib/curl_ed25519.c",
  "vendor/curl/lib/curl_endian.c",
  "vendor/curl/lib/curl_fnmatch.c",
  "vendor/curl/lib/curl_fopen.c",
  "vendor/curl/lib/curl_get_line.c",
  "vendor/curl/lib/curl_gethostname.c",
  "vendor/curl/lib/curl_gssapi.c",
  "vendor/curl/lib/curl_memrchr.c",
  "vendor/curl/lib/curl_ntlm_core.c",
  "vendor/curl/lib/curl_range.c",
  "vendor/curl/lib/curl_sasl.c",
  "vendor/curl/lib/curl_sha512_256.c",
  "vendor/curl/lib/curl_share.c",
  "vendor/curl/lib/curl_sspi.c",
  "vendor/curl/lib/curl_threads.c",
  "vendor/curl/lib/curl_trc.c",
  "vendor/curl/lib/curlx/base64.c",
  "vendor/curl/lib/curlx/basename.c",
  "vendor/curl/lib/curlx/dynbuf.c",
  "vendor/curl/lib/curlx/fopen.c",
  "vendor/curl/lib/curlx/inet_ntop.c",
  "vendor/curl/lib/curlx/inet_pton.c",
  "vendor/curl/lib/curlx/multibyte.c",
  "vendor/curl/lib/curlx/nonblock.c",
  "vendor/curl/lib/curlx/snprintf.c",
  "vendor/curl/lib/curlx/strcopy.c",
  "vendor/curl/lib/curlx/strdup.c",
  "vendor/curl/lib/curlx/strerr.c",
  "vendor/curl/lib/curlx/strparse.c",
  "vendor/curl/lib/curlx/timediff.c",
  "vendor/curl/lib/curlx/timeval.c",
  "vendor/curl/lib/curlx/version_win32.c",
  "vendor/curl/lib/curlx/wait.c",
  "vendor/curl/lib/curlx/warnless.c",
  "vendor/curl/lib/curlx/winapi.c",
  "vendor/curl/lib/cw-out.c",
  "vendor/curl/lib/cw-pause.c",
  "vendor/curl/lib/dict.c",
  "vendor/curl/lib/dynhds.c",
  "vendor/curl/lib/easy.c",
  "vendor/curl/lib/easygetopt.c",
  "vendor/curl/lib/easyoptions.c",
  "vendor/curl/lib/escape.c",
  "vendor/curl/lib/fake_addrinfo.c",
  "vendor/curl/lib/file.c",
  "vendor/curl/lib/fileinfo.c",
  "vendor/curl/lib/formdata.c",
  "vendor/curl/lib/ftp.c",
  "vendor/curl/lib/ftplistparser.c",
  "vendor/curl/lib/getenv.c",
  "vendor/curl/lib/getinfo.c",
  "vendor/curl/lib/gopher.c",
  "vendor/curl/lib/hash.c",
  "vendor/curl/lib/headers.c",
  "vendor/curl/lib/hmac.c",
  "vendor/curl/lib/hsts.c",
  "vendor/curl/lib/http.c",
  "vendor/curl/lib/http1.c",
  "vendor/curl/lib/http2.c",
  "vendor/curl/lib/http_aws_sigv4.c",
  "vendor/curl/lib/http_chunks.c",
  "vendor/curl/lib/http_digest.c",
  "vendor/curl/lib/http_httpsig.c",
  "vendor/curl/lib/http_negotiate.c",
  "vendor/curl/lib/http_ntlm.c",
  "vendor/curl/lib/http_proxy.c",
  "vendor/curl/lib/idn.c",
  "vendor/curl/lib/if2ip.c",
  "vendor/curl/lib/imap.c",
  "vendor/curl/lib/ldap.c",
  "vendor/curl/lib/llist.c",
  "vendor/curl/lib/macos.c",
  "vendor/curl/lib/md4.c",
  "vendor/curl/lib/md5.c",
  "vendor/curl/lib/memdebug.c",
  "vendor/curl/lib/mime.c",
  "vendor/curl/lib/mprintf.c",
  "vendor/curl/lib/mqtt.c",
  "vendor/curl/lib/multi.c",
  "vendor/curl/lib/multi_ev.c",
  "vendor/curl/lib/multi_ntfy.c",
  "vendor/curl/lib/netrc.c",
  "vendor/curl/lib/openldap.c",
  "vendor/curl/lib/parsedate.c",
  "vendor/curl/lib/peer.c",
  "vendor/curl/lib/pingpong.c",
  "vendor/curl/lib/pop3.c",
  "vendor/curl/lib/progress.c",
  "vendor/curl/lib/protocol.c",
  "vendor/curl/lib/proxy.c",
  "vendor/curl/lib/psl.c",
  "vendor/curl/lib/rand.c",
  "vendor/curl/lib/ratelimit.c",
  "vendor/curl/lib/request.c",
  "vendor/curl/lib/rtsp.c",
  "vendor/curl/lib/select.c",
  "vendor/curl/lib/sendf.c",
  "vendor/curl/lib/setopt.c",
  "vendor/curl/lib/sha256.c",
  "vendor/curl/lib/slist.c",
  "vendor/curl/lib/smb.c",
  "vendor/curl/lib/smtp.c",
  "vendor/curl/lib/socketpair.c",
  "vendor/curl/lib/socks.c",
  "vendor/curl/lib/socks_gssapi.c",
  "vendor/curl/lib/socks_sspi.c",
  "vendor/curl/lib/splay.c",
  "vendor/curl/lib/strcase.c",
  "vendor/curl/lib/strequal.c",
  "vendor/curl/lib/strerror.c",
  "vendor/curl/lib/system_win32.c",
  "vendor/curl/lib/telnet.c",
  "vendor/curl/lib/tftp.c",
  "vendor/curl/lib/thrdpool.c",
  "vendor/curl/lib/thrdqueue.c",
  "vendor/curl/lib/transfer.c",
  "vendor/curl/lib/uint-bset.c",
  "vendor/curl/lib/uint-hash.c",
  "vendor/curl/lib/uint-hashset.c",
  "vendor/curl/lib/uint-spbset.c",
  "vendor/curl/lib/uint-table.c",
  "vendor/curl/lib/url.c",
  "vendor/curl/lib/urlapi.c",
  "vendor/curl/lib/vauth/cleartext.c",
  "vendor/curl/lib/vauth/cram.c",
  "vendor/curl/lib/vauth/digest.c",
  "vendor/curl/lib/vauth/digest_sspi.c",
  "vendor/curl/lib/vauth/gsasl.c",
  "vendor/curl/lib/vauth/krb5_gssapi.c",
  "vendor/curl/lib/vauth/krb5_sspi.c",
  "vendor/curl/lib/vauth/ntlm.c",
  "vendor/curl/lib/vauth/ntlm_sspi.c",
  "vendor/curl/lib/vauth/oauth2.c",
  "vendor/curl/lib/vauth/spnego_gssapi.c",
  "vendor/curl/lib/vauth/spnego_sspi.c",
  "vendor/curl/lib/vauth/vauth.c",
  "vendor/curl/lib/vdns/asyn-ares.c",
  "vendor/curl/lib/vdns/asyn-base.c",
  "vendor/curl/lib/vdns/asyn-thrdd.c",
  "vendor/curl/lib/vdns/cf-dns.c",
  "vendor/curl/lib/vdns/dnscache.c",
  "vendor/curl/lib/vdns/doh.c",
  "vendor/curl/lib/vdns/hostip.c",
  "vendor/curl/lib/vdns/hostip4.c",
  "vendor/curl/lib/vdns/hostip6.c",
  "vendor/curl/lib/vdns/httpsrr.c",
  "vendor/curl/lib/version.c",
  "vendor/curl/lib/vquic/capsule.c",
  "vendor/curl/lib/vquic/cf-capsule.c",
  "vendor/curl/lib/vquic/cf-ngtcp2-cmn.c",
  "vendor/curl/lib/vquic/cf-ngtcp2-proxy.c",
  "vendor/curl/lib/vquic/cf-ngtcp2.c",
  "vendor/curl/lib/vquic/cf-quiche.c",
  "vendor/curl/lib/vquic/vquic-tls.c",
  "vendor/curl/lib/vquic/vquic.c",
  "vendor/curl/lib/vssh/libssh.c",
  "vendor/curl/lib/vssh/libssh2.c",
  "vendor/curl/lib/vssh/vssh.c",
  "vendor/curl/lib/vtls/apple.c",
  "vendor/curl/lib/vtls/cipher_suite.c",
  "vendor/curl/lib/vtls/gtls.c",
  "vendor/curl/lib/vtls/hostcheck.c",
  "vendor/curl/lib/vtls/keylog.c",
  "vendor/curl/lib/vtls/mbedtls.c",
  "vendor/curl/lib/vtls/openssl.c",
  "vendor/curl/lib/vtls/rustls.c",
  "vendor/curl/lib/vtls/schannel.c",
  "vendor/curl/lib/vtls/schannel_verify.c",
  "vendor/curl/lib/vtls/vtls.c",
  "vendor/curl/lib/vtls/vtls_config.c",
  "vendor/curl/lib/vtls/vtls_scache.c",
  "vendor/curl/lib/vtls/vtls_spack.c",
  "vendor/curl/lib/vtls/wolfssl.c",
  "vendor/curl/lib/vtls/x509asn1.c",
  "vendor/curl/lib/ws.c",
  "vendor/curl/src/config2setopts.c",
  "vendor/curl/src/slist_wc.c",
  "vendor/curl/src/terminal.c",
  "vendor/curl/src/tool_cb_dbg.c",
  "vendor/curl/src/tool_cb_hdr.c",
  "vendor/curl/src/tool_cb_prg.c",
  "vendor/curl/src/tool_cb_rea.c",
  "vendor/curl/src/tool_cb_see.c",
  "vendor/curl/src/tool_cb_soc.c",
  "vendor/curl/src/tool_cb_wrt.c",
  "vendor/curl/src/tool_cfgable.c",
  "vendor/curl/src/tool_dirhie.c",
  "vendor/curl/src/tool_doswin.c",
  "vendor/curl/src/tool_easysrc.c",
  "vendor/curl/src/tool_filetime.c",
  "vendor/curl/src/tool_findfile.c",
  "vendor/curl/src/tool_formparse.c",
  "vendor/curl/src/tool_getparam.c",
  "vendor/curl/src/tool_getpass.c",
  "vendor/curl/src/tool_help.c",
  "vendor/curl/src/tool_helpers.c",
  "vendor/curl/src/tool_ipfs.c",
  "vendor/curl/src/tool_libinfo.c",
  "vendor/curl/src/tool_listhelp.c",
  "vendor/curl/src/tool_main.c",
  "vendor/curl/src/tool_msgs.c",
  "vendor/curl/src/tool_operate.c",
  "vendor/curl/src/tool_operhlp.c",
  "vendor/curl/src/tool_paramhlp.c",
  "vendor/curl/src/tool_parsecfg.c",
  "vendor/curl/src/tool_progress.c",
  "vendor/curl/src/tool_setopt.c",
  "vendor/curl/src/tool_ssls.c",
  "vendor/curl/src/tool_stderr.c",
  "vendor/curl/src/tool_urlglob.c",
  "vendor/curl/src/tool_util.c",
  "vendor/curl/src/tool_vms.c",
  "vendor/curl/src/tool_writeout.c",
  "vendor/curl/src/tool_writeout_json.c",
  "vendor/curl/src/tool_xattr.c",
  "vendor/curl/src/var.c",
  "vendor/curl/src/toolx/tool_time.c",
  "target/darwin-arm64/tool_hugehelp.c",
]
include-paths = [
  "target/darwin-arm64",
  "vendor/curl/include",
  "vendor/curl/lib",
  "vendor/curl/src",
  "/opt/homebrew/opt/openssl@3/include",
  "/opt/homebrew/opt/libssh2/include",
  "/opt/homebrew/opt/libnghttp2/include",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/21/include",
  "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks",
]
prefixes = [
  "../../dialects/c/target/darwin-arm64.h",
  "../../dialects/c/target/builtins.h",
]
defines = [
  "BUILDING_LIBCURL",
  "CURL_HIDDEN_SYMBOLS",
  "CURL_STATICLIB",
  "HAVE_CONFIG_H",
  "USE_MANUAL",
]
header-defines = []

[link]
frameworks = ["SystemConfiguration", "CoreFoundation", "CoreServices"]
libs = ["ssl", "crypto", "ssh2", "ldap", "lber", "nghttp2"]
search-paths = ["/opt/homebrew/opt/openssl@3/lib", "/opt/homebrew/opt/libssh2/lib", "/opt/homebrew/opt/libnghttp2/lib"]
